
name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        for i in $(find */Cargo.toml )
        do 
            n=$(dirname $i)
            cd $n
            echo "cd $n && cargo build"
            cargo build --verbose
            cd ../
        done
    - name: Run tests
      run: |
        for i in $(find */Cargo.toml )
        do 
            n=$(dirname $i)
            cd $n
            echo "cd $n && cargo test"
            cargo test --verbose
            cd ../
        done

